[project]
name = "quickpythontest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "pandas-stubs>=2.2.3.250308",
    "pyxirr>=0.10.6",
    "streamlit>=1.45.0",
    "watchdog>=6.0.0",
]
